DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS words;

CREATE TABLE IF NOT EXISTS users (
   id INTEGER PRIMARY KEY, 
   username TEXT, 
   password TEXT,
   admin INTEGER NOT NULL
);

CREATE TABLE words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT NOT NULL UNIQUE,
    definition TEXT NOT NULL,
    dialect TEXT NOT NULL,
    approved INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    word_id INTEGER NOT NULL,
    FOREIGN KEY (id) REFERENCES words(id)
);

INSERT INTO users (username, password, admin) VALUES 
('boss', 'boss', 1),
('user', 'user', 0);

INSERT OR IGNORE INTO words (word, definition, dialect, approved) VALUES
('aruk', 'nasi goreng', 'Melanau', 1),
('bagak', 'hebat / besar / bergaya', 'Sarawak Malay', 1),
('bedau', 'belum', 'Melanau', 1),
('bek', 'jangan', 'Iban', 1),
('bekelit', 'berbohong / tipu', 'Sarawak Malay', 1),
('belama', 'lama / berlama-lama', 'Melanau', 1),
('berimbai', 'berkibar (macam bendera)', 'Bidayuh', 1),
('bisi', 'ada', 'Iban', 1),
('bujang', 'lelaki muda / belum kahwin', 'Sarawak Malay', 1),
('bujur', 'betul', 'Iban', 1),
('entaban', 'naik / naik ke atas', 'Iban', 1),
('entauk', 'bagi / untuk', 'Iban', 1),
('gerek', 'best / seronok', 'Sarawak Malay', 1),
('jan', 'jangan', 'Melanau', 1),
('kacak', 'cakap', 'Melanau', 1),
('kamek', 'saya', 'Sarawak Malay', 1),
('kelala', 'lupa', 'Bidayuh', 1),
('kitak', 'awak', 'Sarawak Malay', 1),
('kuduk', 'gatal-gatal / ruam', 'Sarawak Malay', 1),
('kupi', 'kopi', 'Iban', 1),
('madah', 'beritahu', 'Melanau', 1),
('malasik', 'comel / manja', 'Bidayuh', 1),
('maok', 'mahu / hendak', 'Sarawak Malay', 1),
('makan', 'makan', 'Bidayuh', 1),
('mari', 'marah', 'Sarawak Malay', 1),
('mensia', 'orang / manusia', 'Sarawak Malay', 1),
('minum', 'minum', 'Bidayuh', 1),
('mun', 'kalau', 'Iban', 1),
('nadai', 'tiada', 'Bidayuh', 1),
('ngan', 'dengan', 'Bidayuh', 1),
('ngansam', 'simpan', 'Melanau', 1),
('ngantos', 'tunggu / menunggu', 'Bidayuh', 1),
('ngasu', 'memburu', 'Iban', 1),
('ngeri', 'menakutkan', 'Sarawak Malay', 1),
('ngiga', 'mencari', 'Iban', 1),
('ngilu', 'sakit bila gigit', 'Bidayuh', 1),
('nyamai', 'sedap / enak', 'Bidayuh', 1),
('nyepit', 'cubit', 'Iban', 1),
('nyin', 'tidur', 'Bidayuh', 1),
('pandei', 'pandai / bijak', 'Sarawak Malay', 1),
('pauk', 'kena / dapat', 'Sarawak Malay', 1),
('sauk', 'ambil', 'Bidayuh', 1),
('sik', 'tidak', 'Sarawak Malay', 1),
('tambuk', 'baling', 'Melanau', 1),
('tegak', 'berdiri', 'Sarawak Malay', 1),
('tedong', 'ular', 'Sarawak Malay', 1),
('tangga', 'lihat / tengok', 'Bidayuh', 1),
('tinduk', 'tidur', 'Iban', 1),
('tok', 'ini', 'Iban', 1),
('tunggu', 'menunggu', 'Bidayuh', 1),
('ya', 'itu', 'Sarawak Malay', 1),
('semampai', 'tinggi dan cantik', 'Sarawak Malay', 1),
('belabak', 'besar sangat', 'Melanau', 1),
('meruan', 'lari tak tentu arah', 'Iban', 1),
('munyi', 'senyap', 'Bidayuh', 1),
('gat', 'sangat', 'Sarawak Malay', 1),
('tutu', 'tutup', 'Melanau', 1),
('kaban', 'kawan', 'Iban', 1),
('sabar', 'sabar', 'Bidayuh', 1),
('gendang', 'berbunyi / bising', 'Melanau', 1),
('bajik', 'baik', 'Iban', 1),
('suka', 'suka', 'Sarawak Malay', 1),
('dang', 'jangan', 'Iban', 1),
('sapa', 'siapa', 'Sarawak Malay', 1),
('jalai', 'jalan', 'Iban', 1),
('tusah', 'susah', 'Sarawak Malay', 1),
('laju', 'cepat', 'Bidayuh', 1),
('berani', 'berani', 'Sarawak Malay', 1),
('malas', 'malas', 'Melanau', 1),
('lemai', 'sedap', 'Melanau', 1),
('laban', 'kerana', 'Iban', 1),
('ulang', 'ulang', 'Bidayuh', 1),
('terkubak', 'berlumpur', 'Melanau', 1),
('mimang', 'memang', 'Sarawak Malay', 1),
('sayok', 'boleh', 'Bidayuh', 1),
('sedia', 'sedia', 'Sarawak Malay', 1),
('buka', 'buka', 'Melanau', 1),
('gila', 'gila', 'Sarawak Malay', 1),
('cuba', 'cuba', 'Melanau', 1),
('naik', 'naik', 'Iban', 1),
('jatuh', 'jatuh', 'Bidayuh', 1),
('kedak', 'macam', 'Sarawak Malay', 1),
('tapi', 'tetapi', 'Sarawak Malay', 1),
('kitai', 'kita', 'Iban', 1),
('sigek', 'satu', 'Iban', 1),
('nyau', 'sudah', 'Iban', 1),
('tua', 'tua', 'Sarawak Malay', 1),
('nang', 'memang', 'Sarawak Malay', 1),
('bau', 'baru', 'Iban', 1),
('lalu', 'selalu', 'Sarawak Malay', 1),
('terima', 'terima', 'Melanau', 1)