DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS words;

CREATE TABLE IF NOT EXISTS users (
   id INTEGER PRIMARY KEY, 
   username TEXT, 
   password TEXT,
   admin INTEGER NOT NULL
);

CREATE TABLE words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT NOT NULL UNIQUE,
    definition TEXT NOT NULL,
    dialect TEXT NOT NULL,
    approved INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    word_id INTEGER NOT NULL,
    FOREIGN KEY (id) REFERENCES words(id)
);

INSERT INTO users (username, password, admin) VALUES 
('boss', 'boss', 1),
('user', 'user', 0);

INSERT OR IGNORE INTO words (word, definition, dialect, approved) VALUES
('aruk', 'nasi goreng', 'Melanau', 1),
('bagak', 'hebat / besar / bergaya', 'Sarawak Malay', 1),
('bedau', 'belum', 'Melanau', 1),
('bek', 'jangan', 'Iban', 1),
('bekelit', 'berbohong / tipu', 'Sarawak Malay', 1),
('belama', 'lama / berlama-lama', 'Melanau', 1),
('berimbai', 'berkibar (macam bendera)', 'Bidayuh', 1),
('bisi', 'ada', 'Iban', 1),
('bujang', 'lelaki muda / belum kahwin', 'Sarawak Malay', 1),
('bujur', 'betul', 'Iban', 1),
('entaban', 'naik / naik ke atas', 'Iban', 1),
('entauk', 'bagi / untuk', 'Iban', 1),
('gerek', 'best / seronok', 'Sarawak Malay', 1),
('jan', 'jangan', 'Melanau', 1),
('kacak', 'cakap', 'Melanau', 1),
('kamek', 'saya', 'Sarawak Malay', 1),
('kelala', 'lupa', 'Bidayuh', 1),
('kitak', 'awak', 'Sarawak Malay', 1),
('kuduk', 'gatal-gatal / ruam', 'Sarawak Malay', 1),
('kupi', 'kopi', 'Iban', 1),
('madah', 'beritahu', 'Melanau', 1),
('malasik', 'comel / manja', 'Bidayuh', 1),
('maok', 'mahu / hendak', 'Sarawak Malay', 1),
('makan', 'makan', 'Bidayuh', 1),
('mari', 'marah', 'Sarawak Malay', 1),
('mensia', 'orang / manusia', 'Sarawak Malay', 1),
('minum', 'minum', 'Bidayuh', 1),
('mun', 'kalau', 'Iban', 1),
('nadai', 'tiada', 'Bidayuh', 1),
('ngan', 'dengan', 'Bidayuh', 1),
('ngansam', 'simpan', 'Melanau', 1),
('ngantos', 'tunggu / menunggu', 'Bidayuh', 1),
('ngasu', 'memburu', 'Iban', 1),
('ngeri', 'menakutkan', 'Sarawak Malay', 1),
('ngiga', 'mencari', 'Iban', 1),
('ngilu', 'sakit bila gigit', 'Bidayuh', 1),
('nyamai', 'sedap / enak', 'Bidayuh', 1),
('nyepit', 'cubit', 'Iban', 1),
('nyin', 'tidur', 'Bidayuh', 1),
('pandei', 'pandai / bijak', 'Sarawak Malay', 1),
('pauk', 'kena / dapat', 'Sarawak Malay', 1),
('sauk', 'ambil', 'Bidayuh', 1),
('sik', 'tidak', 'Sarawak Malay', 1),
('tambuk', 'baling', 'Melanau', 1),
('tegak', 'berdiri', 'Sarawak Malay', 1),
('tedong', 'ular', 'Sarawak Malay', 1),
('tangga', 'lihat / tengok', 'Bidayuh', 1),
('tinduk', 'tidur', 'Iban', 1),
('tok', 'ini', 'Iban', 1),
('tunggu', 'menunggu', 'Bidayuh', 1),
('ya', 'itu', 'Sarawak Malay', 1),
('semampai', 'tinggi dan cantik', 'Sarawak Malay', 1),
('belabak', 'besar sangat', 'Melanau', 1),
('meruan', 'lari tak tentu arah', 'Iban', 1),
('munyi', 'senyap', 'Bidayuh', 1),
('gat', 'sangat', 'Sarawak Malay', 1),
('tutu', 'tutup', 'Melanau', 1),
('kaban', 'kawan', 'Iban', 1),
('sabar', 'sabar', 'Bidayuh', 1),
('gendang', 'berbunyi / bising', 'Melanau', 1),
('bajik', 'baik', 'Iban', 1),
('suka', 'suka', 'Sarawak Malay', 1),
('dang', 'jangan', 'Iban', 1),
('sapa', 'siapa', 'Sarawak Malay', 1),
('jalai', 'jalan', 'Iban', 1),
('tusah', 'susah', 'Sarawak Malay', 1),
('laju', 'cepat', 'Bidayuh', 1),
('berani', 'berani', 'Sarawak Malay', 1),
('malas', 'malas', 'Melanau', 1),
('lemai', 'sedap', 'Melanau', 1),
('laban', 'kerana', 'Iban', 1),
('ulang', 'ulang', 'Bidayuh', 1),
('terkubak', 'berlumpur', 'Melanau', 1),
('mimang', 'memang', 'Sarawak Malay', 1),
('sayok', 'boleh', 'Bidayuh', 1),
('sedia', 'sedia', 'Sarawak Malay', 1),
('buka', 'buka', 'Melanau', 1),
('gila', 'gila', 'Sarawak Malay', 1),
('cuba', 'cuba', 'Melanau', 1),
('naik', 'naik', 'Iban', 1),
('jatuh', 'jatuh', 'Bidayuh', 1),
('kedak', 'macam', 'Sarawak Malay', 1),
('tapi', 'tetapi', 'Sarawak Malay', 1),
('kitai', 'kita', 'Iban', 1),
('sigek', 'satu', 'Iban', 1),
('nyau', 'sudah', 'Iban', 1),
('tua', 'tua', 'Sarawak Malay', 1),
('nang', 'memang', 'Sarawak Malay', 1),
('bau', 'baru', 'Iban', 1),
('lalu', 'selalu', 'Sarawak Malay', 1),
('terima', 'terima', 'Melanau', 1),
('agak', 'bertemu', 'Sarawak Malay', 1),
('kelakar', 'cakap / bercakap', 'Sarawak Malay', 1),
('tangga', 'lihat / tengok', 'Sarawak Malay', 1),
('tikam', 'baling', 'Sarawak Malay', 1),
('tetak', 'ketawa', 'Sarawak Malay', 1),
('marak', 'membuang', 'Sarawak Malay', 1),
('gaok', 'marah', 'Sarawak Malay', 1),
('kaler', 'warna / colour', 'Sarawak Malay', 1),
('henpon', 'telefon', 'Sarawak Malay', 1),
('sepuloh', 'sepuluh (10)', 'Sarawak Malay', 1),
('duak', 'dua (2)', 'Sarawak Malay', 1),
('tiga', 'tiga (3)', 'Sarawak Malay', 1),
('limak', 'lima (5)', 'Sarawak Malay', 1),
('kenak', 'kenapa / why', 'Sarawak Malay', 1),
('kedak', 'kenyang / full', 'Sarawak Malay', 1),
('kinek', 'sekarang / now', 'Sarawak Malay', 1),
('berambeh', 'singgah / to visit', 'Sarawak Malay', 1),
('cokot', 'berkira / picky', 'Sarawak Malay', 1),
('aok', 'ya / yes', 'Sarawak Malay', 1),
('ngajat', 'tarian Iban', 'Iban', 1),
('ajai', 'tari', 'Iban', 1),
('sumpit', 'senapang tradisional', 'Iban', 1),
('tuak', 'arak beras tradisional', 'Iban', 1),
('tawak', 'gong besar', 'Iban', 1),
('bebendai', 'gong kecil', 'Iban', 1),
('bedup', 'gendang / drum', 'Iban', 1),
('pua kumbu', 'kain tenunan Iban', 'Iban', 1),
('ngasu', 'memburu', 'Iban', 1),
('ngiding', 'menyanyi', 'Iban', 1),
('aku', 'saya / I', 'Iban', 1),
('nuan', 'awak / you', 'Iban', 1),
('aok', 'ya / yes', 'Iban', 1),
('ndak', 'tidak / no', 'Iban', 1),
('ngirup', 'minum / drink', 'Iban', 1),
('lari', 'lari / run', 'Iban', 1),
('meniup', 'blow', 'Iban', 1),
('pangan', 'kawan / friend', 'Iban', 1),
('anak', 'anak / child', 'Iban', 1),
('rumah', 'rumah / house', 'Iban', 1),
('api', 'api / fire', 'Iban', 1),
('ikan', 'ikan / fish', 'Iban', 1),
('burung', 'burung / bird', 'Iban', 1),
('muka', 'muka / face', 'Iban', 1),
('mata', 'mata / eye', 'Iban', 1),
('perut', 'perut / stomach', 'Iban', 1),
('suak', 'suara / voice', 'Iban', 1),
('tepu', 'tutup / close', 'Iban', 1),
('cakap', 'cakap / speak', 'Iban', 1),
('pandang', 'lihat / look', 'Iban', 1),
('agak', 'bertemu', 'Sarawak Malay', 1),
('kelakar', 'cakap / bercakap', 'Sarawak Malay', 1),
('tangga', 'lihat / tengok', 'Sarawak Malay', 1),
('tikam', 'baling / to throw', 'Sarawak Malay', 1),
('tetak', 'ketawa', 'Sarawak Malay', 1),
('marak', 'membuang / to waste', 'Sarawak Malay', 1),
('gaok', 'marah', 'Sarawak Malay', 1),
('kaler', 'warna / colour', 'Sarawak Malay', 1),
('henpon', 'telefon / phone', 'Sarawak Malay', 1),
('sepuloh', 'sepuluh (10)', 'Sarawak Malay', 1),
('duak', 'dua (2)', 'Sarawak Malay', 1),
('tiga', 'tiga (3)', 'Sarawak Malay', 1),
('limak', 'lima (5)', 'Sarawak Malay', 1),
('nam', 'enam (6)', 'Sarawak Malay', 1),
('tujoh', 'tujuh (7)', 'Sarawak Malay', 1),
('lapan', 'lapan (8)', 'Sarawak Malay', 1),
('semilan', 'sembilan (9)', 'Sarawak Malay', 1),
('empat', 'empat (4)', 'Sarawak Malay', 1),
('kenak', 'kenapa / why', 'Sarawak Malay', 1),
('kedak', 'kenyang / full', 'Sarawak Malay', 1),
('kinek', 'sekarang / now', 'Sarawak Malay', 1),
('berambeh', 'singgah / visit', 'Sarawak Malay', 1),
('cokot', 'berkira / picky', 'Sarawak Malay', 1),
('aok', 'ya / yes', 'Sarawak Malay', 1),
('bol', 'bola / ball', 'Sarawak Malay', 1),
('kapet', 'permaidani / carpet', 'Sarawak Malay', 1),
('pancet', 'pecah / punctured (tyre)', 'Sarawak Malay', 1),
('moto', 'motor', 'Sarawak Malay', 1),
('uren', 'oren / orange (fruit)', 'Sarawak Malay', 1),
('raun', 'bulat / round', 'Sarawak Malay', 1),
('bodoh', 'stupid', 'Sarawak Malay', 1),
('berekot', 'berlari / run', 'Sarawak Malay', 1),
('gadong', 'hijau / green', 'Sarawak Malay', 1),
('lawa', 'sombong / arrogant', 'Sarawak Malay', 1),
('paloi', 'bodoh / stupid', 'Sarawak Malay', 1),
('juak', 'juga / also', 'Sarawak Malay', 1),
('si', 'tak / not', 'Sarawak Malay', 1),
('bulak', 'tipu / lie', 'Sarawak Malay', 1),
('nyapu', 'menyapu / sweep', 'Sarawak Malay', 1),
('kelapa', 'nyior / coconut', 'Sarawak Malay', 1),
('lagi', 'lagik / more', 'Sarawak Malay', 1),
('jeraya', 'jalan raya / road', 'Sarawak Malay', 1),
('pandei', 'pandai / clever', 'Sarawak Malay', 1),
('ngaja', 'mengajar / teach', 'Sarawak Malay', 1),
('pusak', 'kucing / cat', 'Sarawak Malay', 1),
('asuk', 'anjing / dog', 'Sarawak Malay', 1),
('manok', 'ayam / chicken', 'Sarawak Malay', 1),
('eksen', 'action', 'Sarawak Malay', 1),
('kapal', 'kapal terbang / aeroplane', 'Sarawak Malay', 1),
('belon', 'balloon', 'Sarawak Malay', 1),
('ngajat', 'tarian Iban', 'Iban', 1),
('ajai', 'tari / dance', 'Iban', 1),
('sumpit', 'senapang tradisional', 'Iban', 1),
('tuak', 'arak beras tradisional', 'Iban', 1),
('tawak', 'gong besar', 'Iban', 1),
('bebendai', 'gong kecil', 'Iban', 1),
('bedup', 'gendang / drum', 'Iban', 1),
('etuai rumah', 'ketua rumah panjang', 'Iban', 1),
('ngasu', 'memburu / hunt', 'Iban', 1),
('ngiding', 'menyanyi / sing', 'Iban', 1),
('aku', 'I / saya', 'Iban', 1),
('nuan', 'you', 'Iban', 1),
('ndak', 'no / tidak', 'Iban', 1),
('ngirup', 'minum / drink', 'Iban', 1),
('lari', 'lari / run', 'Iban', 1),
('pangan', 'kawan / friend', 'Iban', 1),
('anak', 'anak / child', 'Iban', 1),
('rumah', 'rumah / house', 'Iban', 1),
('api', 'api / fire', 'Iban', 1),
('ikan', 'ikan / fish', 'Iban', 1),
('burung', 'burung / bird', 'Iban', 1),
('mata', 'mata / eye', 'Iban', 1),
('perut', 'perut / stomach', 'Iban', 1),
('suak', 'suara / voice', 'Iban', 1),
('tepu', 'tutup / close', 'Iban', 1),
('cakap', 'cakap / speak', 'Iban', 1),
('pandang', 'lihat / look', 'Iban', 1),
('san', 'one (1)', 'Iban', 1),
('duan', 'two (2)', 'Iban', 1),
('dangku', 'three (3)', 'Iban', 1),
('dangkan', 'four (4)', 'Iban', 1),
('dana', 'five (5)', 'Iban', 1),
('tunggul', 'six (6)', 'Iban', 1),
('tuchung', 'seven (7)', 'Iban', 1),
('dalun', 'eight (8)', 'Iban', 1),
('dunggau', 'nine (9)', 'Iban', 1),
('dupuk', 'ten (10)', 'Iban', 1),
('apai', 'father', 'Iban', 1),
('indai', 'mother', 'Iban', 1),
('aki', 'grandfather', 'Iban', 1),
('ini', 'grandmother', 'Iban', 1),
('aya', 'uncle', 'Iban', 1),
('ibu', 'aunt', 'Iban', 1),
('ucen', 'children', 'Iban', 1),
('aku kak', 'I want', 'Iban', 1),
('tunu', 'burn / smoke', 'Iban', 1),
('tubu', 'bamboo shoots', 'Iban', 1),
('rugum', 'beard', 'Iban', 1),
('katil', 'bed', 'Iban', 1),
('capi', 'beef', 'Iban', 1),
('cawan', 'cup', 'Iban', 1),
('dapur', 'kitchen', 'Iban', 1),
('pusu', 'little dried fish', 'Iban', 1),
('kerusi', 'chair', 'Iban', 1),
('panas', 'hot', 'Iban', 1),
('aus', 'thirsty', 'Iban', 1),
('bah', 'flood', 'Iban', 1),
('tulang', 'bone', 'Iban', 1),
('daging', 'meat', 'Iban', 1),
('bini', 'wife', 'Iban', 1),
('babi', 'pig/pork', 'Iban', 1),
('sudu', 'spoon', 'Iban', 1),
('tikai', 'mat', 'Iban', 1),
 ("banar", "benar / betul", "Sarawak Malay", 1),
    ("serang", "marah / menyerang", "Sarawak Malay", 1),
    ("ngaga", "buka / open", "Iban", 1),
    ("nyin", "tidur / sleep", "Bidayuh", 1),
    ("mukah", "muka / face", "Melanau", 1),
    ("silek", "sikit / little", "Sarawak Malay", 1),
    ("tuju", "pergi / go", "Sarawak Malay", 1),
    ("guguk", "anjing / dog", "Bidayuh", 1),
    ("ngigu", "sakit gigi / toothache", "Sarawak Malay", 1),
    ("senangin", "ikan laut / sea fish", "Melanau", 1),
    ("rantau", "merantau / travel", "Sarawak Malay", 1),
    ("seluar", "pants / trousers", "Sarawak Malay", 1),
    ("jemu", "bosan / boring", "Sarawak Malay", 1),
    ("pansuh", "masak dalam buluh / bamboo cooking", "Iban", 1),
    ("salai", "panggang / grill", "Bidayuh", 1),
    ("ngensu", "menyenduk / to scoop", "Melanau", 1),
    ("bagak", "berani / brave", "Iban", 1),
    ("mambang", "hantu / ghost", "Sarawak Malay", 1),
    ("kelun", "orang / person", "Iban", 1),
    ("tinggal", "tinggal / stay", "Sarawak Malay", 1),
    ("lampuk", "pecah / broken", "Sarawak Malay", 1),
    ("sungkei", "buka puasa / break fast", "Sarawak Malay", 1),
    ("tusok", "cucuk / stab", "Sarawak Malay", 1),
    ("ngurai", "bercakap / to speak", "Iban", 1),
    ("ngegeh", "degil / stubborn", "Sarawak Malay", 1),
    ("sakup", "tersepit / jammed", "Bidayuh", 1),
    ("tindih", "tekan / press", "Sarawak Malay", 1),
    ("buang", "buang / throw away", "Sarawak Malay", 1),
    ("belit", "pusing / twist", "Sarawak Malay", 1),
    ("serebu", "habuk / dust", "Sarawak Malay", 1),
    ("gugur", "jatuh / fall", "Sarawak Malay", 1),
    ("lendir", "lendir / mucus", "Sarawak Malay", 1),
    ("cirit", "cirit-birit / diarrhea", "Sarawak Malay", 1),
    ("mati", "mati / die", "Sarawak Malay", 1),
    ("bangun", "bangun / wake up", "Sarawak Malay", 1),
    ("hujan", "hujan / rain", "Sarawak Malay", 1),
    ("berapok", "berpeluh / sweaty", "Sarawak Malay", 1),
    ("sejuk", "sejuk / cold", "Sarawak Malay", 1),
    ("panas", "panas / hot", "Sarawak Malay", 1),
    ("karan", "elektrik / electric", "Sarawak Malay", 1),
    ("peti", "peti sejuk / fridge", "Sarawak Malay", 1),
    ("nasi", "nasi / rice", "Sarawak Malay", 1),
    ("garam", "garam / salt", "Sarawak Malay", 1),
    ("gula", "gula / sugar", "Sarawak Malay", 1),
    ("susu", "susu / milk", "Sarawak Malay", 1),
    ("berani", "berani / brave", "Sarawak Malay", 1),
    ("baju", "baju / shirt", "Sarawak Malay", 1),
    ("selipar", "selipar / slippers", "Sarawak Malay", 1),
    ("kain", "kain / cloth", "Sarawak Malay", 1),
    ("pokok", "pokok / tree", "Sarawak Malay", 1),
    ("daun", "daun / leaf", "Sarawak Malay", 1);


